version: '3.4'

services:
  api:
    build: ./api/
    volumes:
      - ./api/:/usr/src/app
    ports:
      - 5000:80
  site:
    build: ./site/
    volumes:
      - ./site/:/usr/src/app
    ports:
      - 8050:8050
    depends_on:
      - api
  tests:
    build: ./Tests/
    volumes:
      - ./Tests/:/usr/src/app
    depends_on:
      - site
      
